# # FPGA I2C buses

# set_property PACKAGE_PIN BF29 [get_ports F_I2C0_SDA]
# set_property PACKAGE_PIN BF28 [get_ports F_I2C0_SCL]
# set_property PACKAGE_PIN BF27 [get_ports F_I2C1_SDA]
# set_property PACKAGE_PIN BE27 [get_ports F_I2C1_SCL]
# set_property PACKAGE_PIN BC23 [get_ports F_I2C2_SDA]
# set_property PACKAGE_PIN BF20 [get_ports F_I2C2_SCL]
# set_property PACKAGE_PIN BE26 [get_ports F_I2C3_SDA]
# set_property PACKAGE_PIN BD26 [get_ports F_I2C3_SCL]
# set_property PACKAGE_PIN BA28 [get_ports F_I2C4_SDA]
# set_property PACKAGE_PIN BA27 [get_ports F_I2C4_SCL]
# set_property PACKAGE_PIN BE28 [get_ports F_I2C5_SDA]
# set_property PACKAGE_PIN BD28 [get_ports F_I2C5_SCL]
# set_property PACKAGE_PIN AY25 [get_ports F_I2C5_RESET_N]
# set_property PACKAGE_PIN AW25 [get_ports F_I2C5_INT_N]
