# FPGA I2C buses

# set_property IOSTANDARD LVCMOS12 [get_ports F_I2C0_SDA]
# set_property DRIVE 2 [get_ports F_I2C0_SDA]
# set_property SLEW SLOW [get_ports F_I2C0_SDA]
# set_property IOSTANDARD LVCMOS12 [get_ports F_I2C0_SCL]
# set_property DRIVE 2 [get_ports F_I2C0_SCL]
# set_property SLEW SLOW [get_ports F_I2C0_SCL]

# set_property IOSTANDARD LVCMOS12 [get_ports F_I2C1_SDA]
# set_property DRIVE 2 [get_ports F_I2C1_SDA]
# set_property SLEW SLOW [get_ports F_I2C1_SDA]
# set_property IOSTANDARD LVCMOS12 [get_ports F_I2C1_SCL]
# set_property DRIVE 2 [get_ports F_I2C1_SCL]
# set_property SLEW SLOW [get_ports F_I2C1_SCL]

# set_property IOSTANDARD LVCMOS18 [get_ports F_I2C2_SDA]
# set_property DRIVE 2 [get_ports F_I2C2_SDA]
# set_property SLEW SLOW [get_ports F_I2C2_SDA]
# set_property IOSTANDARD LVCMOS18 [get_ports F_I2C2_SCL]
# set_property DRIVE 2 [get_ports F_I2C2_SCL]
# set_property SLEW SLOW [get_ports F_I2C2_SCL]

# set_property IOSTANDARD LVCMOS12 [get_ports F_I2C3_SDA]
# set_property DRIVE 2 [get_ports F_I2C3_SDA]
# set_property SLEW SLOW [get_ports F_I2C3_SDA]
# set_property IOSTANDARD LVCMOS12 [get_ports F_I2C3_SCL]
# set_property DRIVE 2 [get_ports F_I2C3_SCL]
# set_property SLEW SLOW [get_ports F_I2C3_SCL]

# set_property IOSTANDARD LVCMOS12 [get_ports F_I2C4_SDA]
# set_property DRIVE 2 [get_ports F_I2C4_SDA]
# set_property SLEW SLOW [get_ports F_I2C4_SDA]
# set_property IOSTANDARD LVCMOS12 [get_ports F_I2C4_SCL]
# set_property DRIVE 2 [get_ports F_I2C4_SCL]
# set_property SLEW SLOW [get_ports F_I2C4_SCL]

# set_property IOSTANDARD LVCMOS12 [get_ports F_I2C5_SDA]
# set_property DRIVE 8 [get_ports F_I2C5_SDA]
# set_property SLEW SLOW [get_ports F_I2C5_SDA]
# set_property PULLUP true [get_ports F_I2C5_SDA]
# set_property IOSTANDARD LVCMOS12  [get_ports F_I2C5_SCL]
# set_property DRIVE 8 [get_ports F_I2C5_SCL]
# set_property SLEW SLOW [get_ports F_I2C5_SCL]
# set_property IOSTANDARD LVCMOS12  [get_ports F_I2C5_RESET_N]
# set_property DRIVE 2 [get_ports F_I2C5_RESET_N]
# set_property IOSTANDARD LVCMOS12  [get_ports F_I2C5_INT_N]
